# coding: utf-8

"""
    BehaPass

    BehaPass API description  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import behapass_client
from behapass_client.models.user_data import UserData  # noqa: E501
from behapass_client.rest import ApiException


class TestUserData(unittest.TestCase):
    """UserData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserData(self):
        """Test UserData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = behapass_client.models.user_data.UserData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
