# coding: utf-8

"""
    Logger

    Logger API description  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.logger_api import LoggerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLoggerApi(unittest.TestCase):
    """LoggerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.logger_api.LoggerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_button_record(self):
        """Test case for get_button_record

        """
        pass

    def test_get_logger_record(self):
        """Test case for get_logger_record

        """
        pass

    def test_get_movement_record(self):
        """Test case for get_movement_record

        """
        pass

    def test_post_logger_record(self):
        """Test case for post_logger_record

        """
        pass


if __name__ == '__main__':
    unittest.main()
