# coding: utf-8

"""
    Logger

    Logger API description  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.movement_record import MovementRecord  # noqa: E501
from swagger_client.rest import ApiException


class TestMovementRecord(unittest.TestCase):
    """MovementRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMovementRecord(self):
        """Test MovementRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.movement_record.MovementRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
